# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: obiwan
  host: localhost
  timeout: 5000

development:
  <<: *default
  database: friends_ruby_development

test:
  <<: *default
  database: friends_ruby_test

production:
  <<: *default
  database: friends_ruby_production